Thanks to windows, try to run rubocop in bash and output to a json file, then read that from python

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,10 +20,10 @@ inputs:
 outputs:
   summary:
     description: "High level info (number of files checked and number of offenses) from rubocop"
-    value: ${{ steps.run_rubocop.outputs.summary }}
+    value: ${{ steps.analyze_rubocop.outputs.summary }}
   all_output:
     description: "High level info and all annotations from rubocop"
-    value: ${{ steps.run_rubocop.outputs.all_output }}
+    value: ${{ steps.analyze_rubocop.outputs.all_output }}
   rubocop_was_installed:
     description: "For testing purposes mostly, see if rubocop was installed by the action (true) or already installed (false)"
     value: ${{ steps.check_rubocop_installed.outputs.rubocop_was_installed }}
@@ -124,8 +124,15 @@ runs:
           echo "Autocorrect skipped"
         fi
 
+    # Because windows refuses to do subprocess.run(shlex.split('rubocop --format json') even if I supply the full path
+    # So I'm running this step in bash instead of inside the python later...
     - name: run rubocop
-      id: run_rubocop
+      shell: bash
+      run: |
+          rubocop --format json > rubocop.json || true
+
+    - name: Analyze rubocop results
+      id: analyze_rubocop
       shell: python
       run: |
         import os
@@ -167,16 +174,21 @@ runs:
             Also prints the summary data
             """
 
-            result = subprocess.run([r'${{ steps.check_rubocop_installed.outputs.rubocop_path }}', '--format', 'json'],
-                                    capture_output=True)
+            # result = subprocess.run([r'${{ steps.check_rubocop_installed.outputs.rubocop_path }}', '--format', 'json'],
+            #                        capture_output=True)
 
-            if result.returncode == 0:
-                conclusion = 'success'
-            else:
-                conclusion = 'failure'
+            #if result.returncode == 0:
+                #conclusion = 'success'
+            #else:
+                #conclusion = 'failure'
 
-            data = json.loads(result.stdout)
-            print("Rubocop exited with {}: {}".format(result.returncode, conclusion))
+            #data = json.loads(result.stdout)
+            #print("Rubocop exited with {}: {}".format(result.returncode, conclusion))
+
+            with open('rubocop.json', 'r') as f:
+                data = json.load(f)
+            os.remove('rubocop.json')
+
             print(json.dumps(data['summary'], indent=4, sort_keys=True))
             print(f"::set-output name=summary::'{json.dumps(data['summary'])}'")
 
